### ISSUE TITLE
Error reading the symbol_data.npy files 

### ISSUE THREAD

**Issue by mshanak** [AutoLabModena/Panda-Co-Manipulation-Dataset#1]
Hello
Thank you for the dataset, I would like to use it in my paper.

I am trying to run the `python3 load_example.py`  but I get this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 441, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '\x0d'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/r/Downloads/Panda-Co-Manipulation-Dataset/load_example.py", line 13, in <module>
    symbol_data = np.load( "Panda_CoManipulation_Data/06/symbol_data.npy", allow_pickle=True )
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 443, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file 'Panda_CoManipulation_Data/06/symbol_data.npy' as a pickle


```
I tried other `symbol_data.npy `files from other folders, but the same error

**Comment by giobraglia** [comment]
Hi and thanks for the feedback! I think the issue was related to some corrupted files (from 01/symbol_data.npy to 09/symbol_data.npy). Now it should be fixed, please let me know

**Comment by mshanak** [comment]
Thank you

Everything works now, 


![Screenshot from 2024-10-18 09-29-51](https://github.com/user-attachments/assets/6d23ab68-fa2a-4ac9-9231-c79a46863c4a)

**Comment by mshanak** [comment]
I will close this issue
